/**
 * This file was generated by the Jeddict
 */
package com.github.braully.dws.modelo;

import com.github.braully.dws.modelo.Papel;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

/**
 * @author strike
 */
@Entity
public class Usuario {

    @Id
    @GeneratedValue
    private Long id;

    @Basic
    private String nome;

    @Basic
    private String senha;

    @Basic
    private Boolean removido;

    @ManyToMany
    private List<Papel> papeis;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getSenha() {
        return this.senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public Boolean isRemovido() {
        return this.removido;
    }

    public void setRemovido(Boolean removido) {
        this.removido = removido;
    }

    public List<Papel> getPapeis() {
        return this.papeis;
    }

    public void setPapeis(List<Papel> papeis) {
        this.papeis = papeis;
    }

}
